### PR TITLE
Feature/scheme

### PR DESCRIPTION
**Pull request by sergeyshevch**
Changes:
- Added argument for customization schema (my Prometheus available through HTTPS)
- Added Dockerfile
- Upgraded to go 1.18
- Vendored deps

### CODE REVIEW

**Comment by sergeyshevch** [comment]
@hoffie Also i guess it will be great to add Docker image building and deploying examples.

**Comment by hoffie** [comment]
Thanks! Looks good at first glance.

Do you feel confident splitting this up into individual commits?
I think it should be at least four different commits, basically one for each item you've listed above.

**Comment by sergeyshevch** [comment]
@hoffie Sure. I will do it in a week

**Comment by sergeyshevch** [comment]
@hoffie Sorry for the long delay. I had no time to split this and rework PR. Should we close it? We currently use vendored version of this repo in our clusters

**Comment by hoffie** [comment]
I've just added a related function for adjusting the URL scheme in v1.1.12 (via a URL parameter, which allows for per-request decisions). It does not have proper certificate validation yet though. Might add it as needed.
If someone wants to re-test and submit the Dockerfile, I'd also be happy.

As there's no one driving this PR at this time though, I'm closing it for now.

**Pull request closed without merging**
